# Generated by Django 4.2 on 2025-06-04 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uslugi',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
